### ISSUE TITLE
PHP 8.1 Kompabilität

### ISSUE THREAD

**Issue by vossmedien** [ckarisch/ContaoCookieConsentBundle#2]
Hallo zusammen,
ist es möglich die Kompabilität herzustellen? Aktuell einer meiner letzten Erweiterungen die 7.4 benötigen.

Danke!

Viele Grüße,

Christian Voss

**Comment by ckarisch** [comment]
Hallo,

das Plugin unterstützt nun PHP 8.1 und PHP 8.2.

LG

**Comment by ckarisch** [comment]
Issue geschlossen.
